// State de productos

export const OBTENER_PRODUCTOS_EXISTO = "OBTENER_PRODUCTOS_EXITO";

// State para el Pedido

export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const CONFIRMAR_ORDER_PLATE = "CONFIRMAR_ORDER_PLATE";
export const MOSTRAR_RESUMEN = "MOSTRAR_RESUMEN";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const PEDIDO_ORDENADO = "PEDIDO_ORDENADO";